Modified UserProject Model to handle invitations - #272
FelipePSoares/EconoFlow pull request #288
Opened 2024-12-08 08:16 UTC by saksham-malhotra-27

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization

## Description
Added some properties to _UserProject_ Model to be possible work with invitation in the projects.

- Related Issue #272
- Closes #272

2024-12-08 08:29 UTC, saksham-malhotra-27 commented
I think I understand why this is happening now. It's because I changed the logic to throw an error when both the user and email are null.

2024-12-08 08:34 UTC, FelipePSoares requested changes
Nice work, 

Just some suggestions.

2024-12-08 08:34 UTC, FelipePSoares commented on EasyFinance.Domain/AccessControl/UserProject.cs
> +        public DateTime ExpiryDate { get; set; }
```suggestion
        public Guid Token { get; private set; }     
        public bool Accepted { get; private set; }        
        public DateTime SentAt { get; private set; }       
        public DateTime? AcceptedAt { get; private set; }
        public bool Expired { get; private set; } 
        public DateTime ExpiryDate { get; private set; } 
```

All the models in this project has private set and you need to create a method to add the value and in this method before add the new value you will validate if the value is valid. The objetive here is use strong domains that keep valid eachself. 

You can also add in contructor each value to be added in the creation of the model calling this internal method to validate the values.

If you need some example you can look any model in this project.

2024-12-08 08:34 UTC, FelipePSoares commented on EasyFinance.Persistence/Mapping/AccessControl/UserProjectConfiguration.cs
>                  .IsRequired();
```suggestion
                .WithMany();
```

I suggest you to remove this `isRequired` tag from user thinking that now the user can be null.

2024-12-08 12:52 UTC, FelipePSoares commented
Hey @saksham-malhotra-27!

Let me know if you have some doubt.

2024-12-08 13:22 UTC, saksham-malhotra-27 commented
@FelipePSoares little busy today

2024-12-08 13:26 UTC, FelipePSoares commented
@saksham-malhotra-27 no worries. Take your time.

2024-12-08 17:31 UTC, saksham-malhotra-27 commented
Hey @FelipePSoares ! The error occurred because I was throwing an error when both the user and email were null in the constructor. So, in the tests where the user is null and there is no email, we'll receive that error instead of the predefined ones.

2024-12-08 17:42 UTC, FelipePSoares commented
Yeah, probably yes, you are free to change the tests now that the behavior in the application changes no problem.

And for the validation message, please use the validationMessages inside the infrastructure project.

2024-12-08 17:51 UTC, saksham-malhotra-27 commented
For now, I have removed the error that was being thrown when both user and email were null and now nothing is giving an error in build. However, I would prefer if you could handle and update the validations and backend tests for this, as I'm a bit confused by .NET and may not be at my best due to feeling sick at the moment.
@FelipePSoares  thank you! Perhaps you can merge this one if the code looks right and then create a new issue for writing tests for this.

2024-12-08 18:01 UTC, FelipePSoares commented
@saksham-malhotra-27 ,

Don't worry I'll finish this for you. Thank you very much for all your help with this task.

Get well soon.

2024-12-10 07:48 UTC, FelipePSoares approved these changes

2024-12-10 07:49 UTC, merged

2024-12-10 07:50 UTC, FelipePSoares commented
Hey @saksham-malhotra-27 !

I finish it today. Thank you for your help again. 

Have a nice week.

2024-12-10 11:17 UTC, saksham-malhotra-27 commented
No problem @FelipePSoares and thank you for completing it !